NanjilERP/Areas/Transport/Controllers/TransportMasterController.cs
using DAL;
using Microsoft.AspNet.Identity;
using Model.Transport;
using NanjilERP.Areas.Transport.Models;
using NanjilERP.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace NanjilERP.Areas.Transport.Controllers
{
    public class TransportMasterController : Controller
    {
        private NanjilContext db = new NanjilContext();
        ApplicationDbContext appdb = new ApplicationDbContext();


        #region VehicleBrand
        public async Task<ActionResult> BrandList()
        {
            return View(await db.vehicleBrands.ToListAsync());
        }

        public ActionResult BrandCreate()
        {
            return PartialView("_BrandCreate");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BrandCreate([Bind(Include = "VehicleBrandId,BrandName,IsActive")] VehicleBrand brand)
        {
           
            if (ModelState.IsValid)
            {
                db.vehicleBrands.Add(brand);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }

            return PartialView("_BrandCreate", brand);
        }

        public async Task<ActionResult> BrandEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleBrand brand = await db.vehicleBrands.FindAsync(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return PartialView("_BrandEdit", brand);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BrandEdit([Bind(Include = "VehicleBrandId,BrandName,IsActive")] VehicleBrand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                try
                {
                    await db.SaveChangesAsync();
                }
                catch (Exception e)
                {
                    string s = e.ToString();
                }
                return Json(new { success = true });
            }
            return PartialView("_BrandEdit", brand);
        }
        public ActionResult BrandDeactive(bool confirm, int? id)
        {
            //System.Windows.Forms.MessageBox.Show("Test");
            if (id == null)
            {
                // return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleBrand brand = db.vehicleBrands.Find(id);
            if (brand == null)
            {
                //return HttpNotFound();
            }
            brand.IsActive = false;
            db.SaveChanges();
            return RedirectToAction("BrandList");
        }

        #endregion

        #region VehicleModel
        public async Task<ActionResult> ModelList()
        {
            var modellist = from mdl in db.vehicleModels
                           join vbrd in db.vehicleBrands on mdl.VehicleBrandId equals vbrd.VehicleBrandId
                           select new ModelListVM { VehicleModelId = mdl.VehicleModelId,BrandName=vbrd.BrandName, ModelName = mdl.ModelName, IsActive = mdl.IsActive };
            return View(await modellist.ToListAsync());
        }
        public ActionResult ModelCreate()
        {

            ViewBag.Brands = new SelectList(db.vehicleBrands, "VehicleBrandId", "BrandName");
            return PartialView("_ModelCreate");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ModelCreate([Bind(Include = "VehicleModelId,ModelName,VehicleBrandId,IsActive")] VehicleModel vmodel)
        {
           
            if (ModelState.IsValid)
            {
                db.vehicleModels.Add(vmodel);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }
            ViewBag.Brands = new SelectList(db.vehicleBrands, "VehicleBrandId", "BrandName");
            return PartialView("_ModelCreate", vmodel);
        }
        #endregion
    }
}

NanjilERP/Areas/Transport/Views/TransportMaster/BrandList.cshtml
@model IEnumerable<Model.Transport.VehicleBrand>

@{
    ViewBag.Title = "VehicleBrandList";
    ViewBag.Description = "Admin";

}



<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Brand Lists</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>

                @*@Html.ActionLink("Create New", "BrandCreate")*@
                @Html.ActionLink("Create New", "BrandCreate", "TransportMaster", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Brand Name</th>
                        
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.BrandName)
                            </td>
                            
                            <td>
                                @if (item.IsActive == true)
                                {  <text> Yes</text>}
                                else
                                { <text> No</text> }

                            </td>
                            <td>
                                @Html.ActionLink("Edit", "BrandEdit", new { id = item.VehicleBrandId }, new { data_modal = "" }) |
                                @*@Html.ActionLink("Details", "Details", new { id = item.BrandId }) |*@
                                @Html.ActionLink("Deactive", "BrandDeactive", new { confirm = true, id = item.VehicleBrandId },
                                            new { onclick = "return confirm('Are you sure to deactive Brand?');" })
                            </td>
                        </tr>
                    }

                </tbody>
                <tfoot>
                    <tr>
                        <th>Brand Name</th>
                        
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Transport/Views/TransportMaster/ModelList.cshtml
@model IEnumerable<NanjilERP.Areas.Transport.Models.ModelListVM>

@{
    ViewBag.Title = "ModelList";
}

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Model List</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>

                @*@Html.ActionLink("Create New", "BrandCreate")*@
                @Html.ActionLink("Create New", "ModelCreate", "TransportMaster", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                      
                        <th>Model Name</th>
                        <th>Brand Name</th>
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                           
                            <td>
                                @Html.DisplayFor(modelItem => item.ModelName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BrandName)
                            </td>
                            <td>
                                @if (item.IsActive == true)
                                {  <text> Yes</text>}
                                else
                                { <text> No</text> }
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "ModelEdit", new { id = item.VehicleModelId }, new { data_modal = "" }) |
                                @*@Html.ActionLink("Details", "Details", new { id = item.BrandId }) |*@
                                @Html.ActionLink("Deactive", "ModelDeactive", new { confirm = true, id = item.VehicleModelId },
                                            new { onclick = "return confirm('Are you sure to deactive Type?');" })
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>Model Name</th>
                        <th>Brand Name</th>
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Transport/Views/TransportMaster/_BrandCreate.cshtml
@model Model.Transport.VehicleBrand

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Add new Brand</h4>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.BrandName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.BrandName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BrandName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            
        </div>
    </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal">Cancel</button>
            <input class="btn btn-primary" type="submit" value="Save" />
        </div>
}

     

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

NanjilERP/Areas/Transport/Views/TransportMaster/_BrandEdit.cshtml
@model Model.Transport.VehicleBrand

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Edit Brand</h4>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="modal-body">
        <div class="form-horizontal">
          
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.VehicleBrandId)

            <div class="form-group">
                @Html.LabelFor(model => model.BrandName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BrandName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BrandName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

        
        </div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal">Cancel</button>
            <input class="btn btn-primary" type="submit" value="Save" />
        </div>
        }

     

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

NanjilERP/Areas/Transport/Views/TransportMaster/_ModelCreate.cshtml
@model Model.Transport.VehicleModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Add new Model</h4>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="modal-body">
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.VehicleBrandId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.VehicleBrandId,
                            (IEnumerable<SelectListItem>)ViewBag.Brands,
                            "Select Brand",
                            new { @class = "form-control" })


                    @Html.ValidationMessageFor(model => model.VehicleBrandId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModelName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModelName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ModelName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button class="btn" data-dismiss="modal">Cancel</button>
                <input class="btn btn-primary" type="submit" value="Save" />
            </div>
        </div>
        </div>

        }

    

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }