NanjilERP/Areas/Admin/Controllers/MasterDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using Model;
using System.Net;
using System.Data.Entity;
using System.Threading.Tasks;
using NanjilERP.Models;
using Microsoft.AspNet.Identity;
using NanjilERP.Areas.Admin.Models;

namespace NanjilERP.Areas.Admin.Controllers
{
    public class MasterDetailsController : Controller
    {
        private NanjilContext db = new NanjilContext();
        ApplicationDbContext appdb = new ApplicationDbContext();
        // GET: Admin/MasterDetails
        
        public ActionResult Index()
        {
            
            return View();
        }

        #region Unit
        public async Task<ActionResult> UnitList()
        {
            return View(await db.units.ToListAsync());
        }

        public ActionResult UnitCreate()
        {
            return PartialView("_UnitCreate");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UnitCreate([Bind(Include = "UnitId,UnitName,IsActive")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                db.units.Add(unit);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }

            return PartialView("_UnitCreate", unit);
        }

        public ActionResult EditUnit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = db.units.Find(id);
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUnit([Bind(Include = "UnitId,UnitName,IsActive")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(unit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UnitsLists");
            }
            return View(unit);
        }

        public ActionResult DeactiveUnit(bool confirm, int? id)
        {
            //System.Windows.Forms.MessageBox.Show("Test");
            if (id == null)
            {
                // return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = db.units.Find(id);
            if (unit == null)
            {
                //return HttpNotFound();
            }
            unit.IsActive = false;
            db.SaveChanges();
            return RedirectToAction("UnitsLists");
        }


        #endregion

        #region Brand
        public async Task<ActionResult> BrandList()
        {
            return View(await db.brands.ToListAsync());
        }

        public ActionResult BrandCreate()
        {
            return PartialView("_BrandCreate");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BrandCreate([Bind(Include = "BrandId,BrandName,TinNo,Description,IsActive")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.brands.Add(brand);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }

            return PartialView("_BrandCreate",brand);
        }
        
        public async Task<ActionResult> BrandEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = await db.brands.FindAsync(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return PartialView("_BrandEdit", brand);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BrandEdit([Bind(Include = "BrandId,BrandName,TinNo,Description,IsActive")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                try
                {
                    await db.SaveChangesAsync();
                }
                catch (Exception e)
                {
                    string s = e.ToString();
                }
                return Json(new { success = true });
            }
            return PartialView("_BrandEdit", brand);
        }
        public ActionResult BrandDeactive(bool confirm, int? id)
        {
            //System.Windows.Forms.MessageBox.Show("Test");
            if (id == null)
            {
                // return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.brands.Find(id);
            if (brand == null)
            {
                //return HttpNotFound();
            }
            brand.IsActive = false;
            db.SaveChanges();
            return RedirectToAction("BrandList");
        }

        #endregion

        #region Type
        public async Task<ActionResult> TypesList()
        {
            var typelist = from typ in db.types
                           join brnd in db.brands on typ.BrandId equals brnd.BrandId
                           select new TypeListVM { TypesId = typ.TypesId, BrandName = brnd.BrandName, TypesName = typ.TypesName, IsActive = typ.IsActive };
            return View(await typelist.ToListAsync());
        }

        public ActionResult TypesCreate()
        {

            ViewBag.Brands = new SelectList(db.brands, "BrandId", "BrandName");
            return PartialView("_TypesCreate");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> TypesCreate([Bind(Include = "TypesId,TypesName,BrandId,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate,IsActive")] Types type)
        {
            string userId = User.Identity.GetUserId();
            ApplicationUser currentUser = appdb.Users.FirstOrDefault(x => x.Id == userId);
           
            type.ModifiedDate = DateTime.Now;
            type.CreatedDate = DateTime.Now;
            type.CreatedBy = currentUser.EmployeeId;
            type.ModifiedBy = currentUser.EmployeeId;
            if (ModelState.IsValid)
            {
                db.types.Add(type);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }
            ViewBag.Brands = new SelectList(db.brands, "BrandId", "BrandName");
            return PartialView("_TypesCreate", type);
        }

        public async Task<ActionResult> TypesEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Types type = await db.types.FindAsync(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return PartialView("_TypesEdit", type);
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> BrandEdit([Bind(Include = "BrandId,BrandName,TinNo,Description,IsActive")] Brand brand)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(brand).State = EntityState.Modified;
        //        try
        //        {
        //            await db.SaveChangesAsync();
        //        }
        //        catch (Exception e)
        //        {
        //            string s = e.ToString();
        //        }
        //        return Json(new { success = true });
        //    }
        //    return PartialView("_BrandEdit", brand);
        //}
        //public ActionResult BrandDeactive(bool confirm, int? id)
        //{
        //    //System.Windows.Forms.MessageBox.Show("Test");
        //    if (id == null)
        //    {
        //        // return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Brand brand = db.brands.Find(id);
        //    if (brand == null)
        //    {
        //        //return HttpNotFound();
        //    }
        //    brand.IsActive = false;
        //    db.SaveChanges();
        //    return RedirectToAction("BrandList");
        //}

        #endregion

        #region Commodity
        public async Task<ActionResult> CommodityList()
        {
            var list = from cmd in db.commodities
                        join tp in db.types on cmd.TypesId equals tp.TypesId
                        select new CommodityListVM { CommodityId = cmd.CommodityId, CommodityName = cmd.CommodityName, TypesName = tp.TypesName, IsActive = cmd.IsActive };
            return View(await list.ToListAsync());
        }

        public ActionResult CommodityCreate()
        {
            ViewBag.Types = new SelectList(db.types, "TypesId", "TypesName");
            return PartialView("_CommodityCreate");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CommodityCreate([Bind(Include = "CommodityId,CommodityName,TypesId,IsActive,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate")] Commodity commodity)
        {
            commodity.CreatedBy = 1;
            commodity.ModifiedBy = 1;
            commodity.CreatedDate = DateTime.Now;
            commodity.ModifiedDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.commodities.Add(commodity);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }

            return PartialView("_CommodityCreate", commodity);
        }

        //public async Task<ActionResult> BrandEdit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Brand brand = await db.brands.FindAsync(id);
        //    if (brand == null)

NanjilERP/Areas/Admin/Views/MasterDetails/CommodityList.cshtml
@model IEnumerable<NanjilERP.Areas.Admin.Models.CommodityListVM>

@{
    ViewBag.Title = "CommodityList";
    ViewBag.Description = "Admin";
}

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Commodity List</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>
                @Html.ActionLink("Create New", "CommodityCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Commodity Name</th>
                        <th>Type</th>
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CommodityName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TypesName)
                            </td>
                           
                            <td>
                                @if (item.IsActive == true)
                                {  <text> Yes</text>}
                                else
                                { <text> No</text> }

                            </td>
                            <td>
                                @Html.ActionLink("Edit", "CommodityEdit", new { id = item.CommodityId }, new { data_modal = "" }) |
                                @*@Html.ActionLink("Details", "Details", new { id = item.BrandId }) |*@
                                @Html.ActionLink("Deactive", "CommodityDeactive", new { confirm = true, id = item.CommodityId },
                                            new { onclick = "return confirm('Are you sure to deactive Brand?');" })
                            </td>
                        </tr>
                    }

                </tbody>
                <tfoot>
                    <tr>
                        <th>Commodity Name</th>
                        <th>Type</th>
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Admin/Views/MasterDetails/CountryList.cshtml
@model IEnumerable<Model.Country>

@{
    ViewBag.Title = "Countries List";
    ViewBag.Description = "Admin";
    //ViewBag.Sidebar = "AdminMaster";


}

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>


<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Brand Lists</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>

                @*@Html.ActionLink("Create New", "BrandCreate")*@
                @Html.ActionLink("Create New", "CountryCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Country Name</th>
                        <th>Is Active</th>
                        <th>Action </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CountryName)
                            </td>
                            <td>
                                @if (item.IsActive == true)
                                {  <text> Yes</text>}
                                else
                                { <text> No</text> }

                            </td>
                            <td>
                                @Html.ActionLink("Edit", "CountryEdit", new { id = item.CountryId }, new { data_modal = "" }) |
                                @*@Html.ActionLink("Details", "Details", new { id = item.BrandId }) |*@
                                @Html.ActionLink("Deactive", "CountryDeactive", new { confirm = true, id = item.CountryId },
                                            new { onclick = "return confirm('Are you sure to deactive Country?');" })
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>Country Name</th>
                        <th>Is Active</th>
                        <th>Action </th>
                    </tr>
                    </tfoot>
</table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Admin/Views/MasterDetails/DepartmentList.cshtml
@model IEnumerable<Model.Department>

@{
    ViewBag.Title = "DepartmentList";
    ViewBag.Description = "Admin";
}

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Department Lists</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>

                @*@Html.ActionLink("Create New", "BrandCreate")*@
                @Html.ActionLink("Create New", "DepartmentCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Department </th>
                        <th>Description</th>
                        <th>Is Active</th>
                        <th>Action </th>
                    </tr>
                </thead>
                <tbody>


                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.DepartmentName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.DepartmentId }) |
                                @Html.ActionLink("Details", "Details", new { id = item.DepartmentId }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.DepartmentId })
                            </td>
                        </tr>
                    }

                </tbody>
                <tfoot>

                    <tr>
                        <th>Department </th>
                        <th>Description</th>
                        <th>Is Active</th>
                        <th>Action </th>
                    </tr>

                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Admin/Views/MasterDetails/DistrictList.cshtml
@model IEnumerable<Model.District>

@{
    ViewBag.Title = "DistrictList";
    ViewBag.Description = "Admin";
}

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">District Lists</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>

                @*@Html.ActionLink("Create New", "BrandCreate")*@
                @Html.ActionLink("Create New", "DistrictCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>District </th>
                        <th>State</th>
                        <th>Is Active</th>
                        <th>Action </th>
                    </tr>
                </thead>
                <tbody>
                    

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DistrictName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StateId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsActive)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.DistrictId }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.DistrictId }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.DistrictId })
                                </td>
                            </tr>
                        }

                </tbody>
                <tfoot>
                    
                    <tr>
                        <th>District </th>
                        <th>State</th>
                        <th>Is Active</th>
                        <th>Action </th>
                    </tr>
                   
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Admin/Views/MasterDetails/EmployeeList.cshtml
@model IEnumerable<Model.Employee>

@{
    ViewBag.Title = "EmployeeList";
    ViewBag.Description = "Admin";

}


<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Employee Lists</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>
                @Html.ActionLink("Create New", "EmployeeCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Employee Name</th>
                        <th>Employee Code</th>
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.EmployeeName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EmployeeCode)
                            </td>
                           
                            <td>
                                @if (item.IsActive == true)
                                {  <text> Yes</text>}
                                else
                                { <text> No</text> }

                            </td>
                            <td>
                                @Html.ActionLink("Edit", "EmployeeEdit", new { id = item.EmployeeId }, new { data_modal = "" }) |
                                @*@Html.ActionLink("Details", "Details", new { id = item.BrandId }) |*@
                                @Html.ActionLink("Deactive", "EmployeeDeactive", new { confirm = true, id = item.EmployeeId },
                                            new { onclick = "return confirm('Are you sure to deactive Brand?');" })
                            </td>
                        </tr>
                    }

                </tbody>
                <tfoot>
                    <tr>
                        <th>Employee Name</th>
                        <th>Employee Code</th>
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Admin/Views/MasterDetails/ProductList.cshtml
@model IEnumerable<NanjilERP.Areas.Admin.Models.ProductListVM>

@{
    ViewBag.Title = "ProductList";
    ViewBag.Description = "Admin";
}

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Type List</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>
                @Html.ActionLink("Create New", "ProductCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Commodity</th>
                        <th>Types</th>
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CommodityName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TypeName)
                            </td>
                            <td>
                                @if (item.IsActive == true)
                                {  <text> Yes</text>}
                                else
                                { <text> No</text> }
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "ProductEdit", new { id = item.ProductId }, new { data_modal = "" }) |
                                @*@Html.ActionLink("Details", "Details", new { id = item.BrandId }) |*@
                                @Html.ActionLink("Deactive", "ProductDeactive", new { confirm = true, id = item.ProductId },
                                            new { onclick = "return confirm('Are you sure to deactive Brand?');" })
                            </td>
                        </tr>
                    }

                </tbody>
                <tfoot>
                    <tr>
                        <th>Product</th>
                        <th>Commodity</th>
                        <th>Types</th>
                        <th>Is Active</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Admin/Views/MasterDetails/StateList.cshtml
@model IEnumerable<Model.State>

@{
    ViewBag.Title = "StateList";
    ViewBag.Description = "Admin";
}
<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">State Lists</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>

                @*@Html.ActionLink("Create New", "BrandCreate")*@
                @Html.ActionLink("Create New", "StateCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>State Name</th>
                        <th>Is Active</th>
                        <th>Action </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.StateName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.StateId }) |
                                @Html.ActionLink("Details", "Details", new { id = item.StateId }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.StateId })
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>State Name</th>
                        <th>Is Active</th>
                        <th>Action </th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Admin/Views/MasterDetails/_UnitCreate.cshtml
@model Model.Unit


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Add New Unit</h4>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UnitName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UnitName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UnitName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            
        </div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal">Cancel</button>
            <input class="btn btn-primary" type="submit" value="Save" />
        </div>
}

        

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }