NanjilERP/Areas/Admin/Controllers/ManageUsersController.cs
using NanjilERP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using NanjilERP.Areas.Admin.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using DAL;
using System.Threading.Tasks;

namespace NanjilERP.Areas.Admin.Controllers
{
    public class ManageUsersController : Controller
    {
        ApplicationDbContext db;
        NanjilContext ndb;
       
        public ActionResult Index()
        {

            db = new ApplicationDbContext();
            
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>
               (db));
            
            var users = db.Users.ToList();
           
            var viewModels = new List<UserlistViewModel>();

            foreach (var user in users)
            {
                var s = UserManager.GetRoles(user.Id);
                string rolename = string.Empty;
                try { rolename = s[0].ToString(); }
                catch (Exception ) { rolename = "None"; }
                
                viewModels.Add(new UserlistViewModel { Id = user.Id, Name = user.UserName, Role = rolename });
            }
            return View(viewModels);
        }
        public ActionResult UserCreate()
        {
            ndb = new NanjilContext();
            db = new ApplicationDbContext();
            var emp = ndb.employees
                        .Where(x => x.IsActive == true)
                        .ToList()
                        .Select(x => new { EmployeeId = x.EmployeeId, EmployeeName = string.Format("{0} {1}",x.EmployeeCode, x.EmployeeName) });
            ViewBag.Employees = new SelectList(emp, "EmployeeId", "EmployeeName");
            //ViewBag.Roles = new SelectList(db.Roles, "RoleId", "Role");
            ViewBag.Roles = new SelectList(db.Roles.ToList(), "Name", "Name");

            return PartialView("_UserCreate");
        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UserCreate(UserCreateVM model)
        {
            ndb = new NanjilContext();
            db = new ApplicationDbContext();
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email, EmployeeId=model.EmployeeId };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    // await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                    await this.UserManager.AddToRoleAsync(user.Id, model.RoleId);
                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return Json(new { success = true });
                }
                AddErrors(result);
            }

            var emp = ndb.employees
                        .Where(x => x.IsActive == true)
                        .ToList()
                        .Select(x => new { EmployeeId = x.EmployeeId, EmployeeName = string.Format("{0} {1}", x.EmployeeCode, x.EmployeeName) });
            ViewBag.Employees = new SelectList(emp, "EmployeeId", "EmployeeName");
            ViewBag.Roles = new SelectList(db.Roles.ToList(), "Name", "Name");
            return PartialView("_UserCreate",model);
        }
    }
}

NanjilERP/Areas/Admin/Views/ManageUsers/Index.cshtml
@model IEnumerable<NanjilERP.Areas.Admin.Models.UserlistViewModel>

@{
    ViewBag.Title = "UserList";
    ViewBag.Description = "Admin";
}



<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-header">
            <h3 class="box-title">User Lists</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <p>

                @*@Html.ActionLink("Create New", "BrandCreate")*@
                @Html.ActionLink("Create New", "UserCreate", "ManageUsers", null, new { data_modal = "", id = "btnCreate", @class = "btn-xs btn-success" })
            </p>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>User Name</th>
                        <th>Role</th>

                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Role)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                            </td>
                        </tr>
                    }

                </tbody>
                <tfoot>
                    <tr>
                        <th>User Name</th>
                        <th>Role</th>
                       
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

NanjilERP/Areas/Admin/Views/ManageUsers/_UserCreate.cshtml
@model NanjilERP.Areas.Admin.Models.UserCreateVM

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Add new User</h4>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.EmployeeId,
                            (IEnumerable<SelectListItem>)ViewBag.Employees,
                            "Select Employee",
                            new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                   @Html.DropDownListFor(model => model.RoleId,
                            (IEnumerable<SelectListItem>)ViewBag.Roles,
                            "Select Role",
                            new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            
        </div>
    </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal">Cancel</button>
            <input class="btn btn-primary" type="submit" value="Save" />
        </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}